deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: <JJlcXcFnIFEaie91HzqN5aCOMfP1QHHcfAsQJdoyOuNxpxNEpAm4SPKOG8o41dgf> # your encrypted token from GitHub
  artifact: bin\release\SatIp Rtsp Sample.zip             # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
